services:
  web:
    container_name: amorabi
    build: ./amorabi
    restart: unless-stopped
    volumes:
      - ./amorabi:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"

volumes:
  static_volume:
