services:
  web:
    container_name: amorabi
    build: ./amorabi
    restart: always
    volumes:
      - ./amorabi:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  static_volume:
