# Generated by Django 5.2.1 on 2025-06-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ativo',
        ),
    ]
